Test of Register and Signin.
ACMHomepage/ACMHomepage pull request #23
Opened 2022-03-22 03:19 UTC by TTL2000

I add the test of after Register and Signin return to homepage.

2022-03-22 07:07 UTC, RileyYe approved these changes
approved

2022-03-22 11:15 UTC, PeterlitsZo commented
> approved

Did you review really?

2022-03-22 11:23 UTC, PeterlitsZo commented
Do you really run those tests? Why did they fail?

2022-03-30 09:58 UTC, PeterlitsZo commented
Hello, @TTL2000, here are some suggestions for you:

1. Commit with a good message style. You can click [here](https://github.com/ACMHomepage/ACMHomepage/blob/master/docs/contribute.md) to know more. If you have some questions, please feel free to open an issue to talk about it.
2. If you work on your repository (TTL2000/ACMHomepage) rather than this repository, feel free to use `git rebase` and `git push --force`.
3. Use another branch, for example, `add-test-for-register-and-signin` rather than **`master`**!

2022-03-30 10:29 UTC, PeterlitsZo requested changes

2022-03-30 10:29 UTC, PeterlitsZo commented on front/src/page/Register.test.tsx
> +afterAll(() => server.close());
I think putting those lines into the `jest.setup.ts` will be a better idea.

2022-03-30 10:29 UTC, PeterlitsZo commented on front/src/page/Register.test.tsx
> +  expect(screen.queryByText('__Homepage__')).toBeNull();
Add comments please.

2022-03-30 10:29 UTC, PeterlitsZo commented on front/src/api/auth.ts
> + * Sign up part
Rename to `Register part`

2022-03-30 11:29 UTC, TTL2000 reviewed
OK，and i'd like to know why putting some lines of Register.test.tsx to jest.setup.ts is better!

2022-03-31 09:06 UTC, merged